GET http://localhost:8080/users HTTP/2.0
content-type: application/json

###

POST http://localhost:8080/users HTTP/2.0
content-type: application/json

{
    "username":"test2",
    "email":"hest2@example.com",
    "password":"hestetest2"
}

###

GET http://localhost:8080/users/1 HTTP/2.0
content-type: application/json

###

PUT http://localhost:8080/users/1 HTTP/2.0
content-type: application/json

{
    "email":"hest3@example.com",
}

###

DELETE http://localhost:8080/users/1 HTTP/2.0
content-type: application/json

###